version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /home/node/app/node_modules
      - .:/home/node/app
  tests:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /home/node/app/node_modules
      - .:/home/node/app
    command: ["npm","run","test"]


# Lo ejecutamos con el comando: 
# docker-compose up
# Sustituyendo la linea de comando en consola:
# docker run -it -p 3000:3000 -v /home/node/app/node_modules -v ~/frontend:/home/node/app numeroId-Tag
