# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Create and publish a Docker image

# Con cada push se actualizará
on: push

env:
# Indicamos que cree en Docker Packages
  REGISTRY: ghcr.io
# Una imagen con el mismo nombre que el repositorio-> ${{ github.repository }}
  IMAGE_NAME: blaucel/dockymagen
# Le ponemos un tag personalizado a la imagen: 1.0.número de subida
  IMAGE_TAG: 1.0.${{ github.run_number }}

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

# la dirección en "uses:" es un acceso a la documentación para modificar este workflow
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
# Personalizamos los tags de la imagen subida:
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: |
            ghcr.io/user/app:latest
            ghcr.io/user/app:1.0.0
          labels: ${{ steps.meta.outputs.labels }}
# tags: ${{ steps.meta.outputs.tags }}